### ISSUE TITLE
No module named 'deps.ControlNet.share'

### ISSUE THREAD

**Issue by TechHalloman** [williamyang1991/Rerender_A_Video#100]
File "rerender.py", line 17, in <module>
    import src.import_util  # noqa: F401
  File "/home/ssssss/Documents/Rerender_A_Video-main/src/import_util.py", line 10, in <module>
    import deps.ControlNet.share  # noqa: F401 E402
ModuleNotFoundError: No module named 'deps.ControlNet.share'

**Comment by ronbere** [comment]
same here

**Comment by vijayasvj** [comment]
> File "rerender.py", line 17, in import src.import_util # noqa: F401 File "/home/ssssss/Documents/Rerender_A_Video-main/src/import_util.py", line 10, in import deps.ControlNet.share # noqa: F401 E402 ModuleNotFoundError: No module named 'deps.ControlNet.share'

![image](https://github.com/williamyang1991/Rerender_A_Video/assets/65366176/6ef27896-2f6c-44d7-a37f-6c87770d0c6c)

'-recursive' is important, only then the files in the location Rerender_A_Video/deps/...... will also be cloned in your local machine.

**Comment by ronbere** [comment]
> > File "rerender.py", line 17, in import src.import_util # noqa: F401 File "/home/ssssss/Documents/Rerender_A_Video-main/src/import_util.py", line 10, in import deps.ControlNet.share # noqa: F401 E402 ModuleNotFoundError: No module named 'deps.ControlNet.share'
> 
> ![image](https://user-images.githubusercontent.com/65366176/277169976-6ef27896-2f6c-44d7-a37f-6c87770d0c6c.png)
> 
> '-recursive' is important, only then the files in the location Rerender_A_Video/deps/...... will also be cloned in your local machine.

Right !!! Working fine now
