### ISSUE TITLE
load model failed !

### ISSUE THREAD

**Issue by shihuai** [williamyang1991/Rerender_A_Video#106]
Hello, I want to run the webUI.py, but load model failed. The error message is：
Unexpected key(s) in state_dict: "cond_stage_model.transformer.text_model.embeddings.position_ids".

**Comment by williamyang1991** [comment]
I have no idea.
Maybe you use the wrong transformers version?

**Comment by williamyang1991** [comment]
@youdutaidi  @shihuai 
We direct use the ControlNet code without modification of the text_model.
Maybe you can raise an issue in the ControlNet repertory.

And I found this related [issue](https://github.com/lllyasviel/ControlNet/issues/532) in the ControlNet.
It says just not loading the key to solve this problem.

**Comment by shihuai** [comment]
> > Hello, I want to run the webUI.py, but load model failed. The error message is： Unexpected key(s) in state_dict: "cond_stage_model.transformer.text_model.embeddings.position_ids".
> 
> I have met the same problem. ` File "rerender.py", line 465, in <module> rerender(cfg, args.one, args.key_video_path) File "rerender.py", line 83, in rerender model.load_state_dict( File "/opt/conda/envs/codef/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for ControlLDM: Unexpected key(s) in state_dict: "cond_stage_model.transformer.text_model.embeddings.position_ids".` I am sure that it is not about the wrong transformers version, all models are defined in ControlNet folder.

You can try degrade transformers vision, it works for me.
