### ISSUE TITLE
Will there be a usable model or pipeline in Diffusers?

### ISSUE THREAD

**Issue by sunhaozhepy** [williamyang1991/Rerender_A_Video#118]
Hi,

Thanks for your great work! I read on the project's homepage on GitHub that there will be a Diffusers implementation. May I ask how are things going, and when will the implementation be released? Instead of using the normal ControlNet pipeline, I'm willing to combine ControlNet and img2img to apply your model to my task, and I think it's easier to customize the model with the Diffusers package.

**Comment by williamyang1991** [comment]
The diffuser code is almost done. @SingleZombie maybe ready in this month?

**Comment by sunhaozhepy** [comment]
That is exciting news. Can't wait for the release!
