### ISSUE TITLE
How to install gmflow for Diffusers pipeline?

### ISSUE THREAD

**Issue by sunhaozhepy** [williamyang1991/Rerender_A_Video#121]
I'm trying out the diffusers implementation of your project ([this repo](https://github.com/SingleZombie/diffusers-Rerender)). I see that I need to install gmflow in the root directory. I wonder how I should do that?

**Comment by sunhaozhepy** [comment]
Because there's no way to "install" the package, and wherever I clone the gmflow repo into, the v2v.py script can't find the gmflow module.

**Comment by williamyang1991** [comment]
Did you forget to specify the ``gmflow_dir``

![image](https://github.com/williamyang1991/Rerender_A_Video/assets/18130694/a66078a0-91e9-414a-87a3-0353b554c874)

**Comment by sunhaozhepy** [comment]
I'm sorry but I don't see a `rerender_a_video.py` either in the official Diffusers repo, nor in the forked Diffusers repo in your Diffusers implementation.

**Comment by williamyang1991** [comment]
https://github.com/huggingface/diffusers/blob/main/examples/community/rerender_a_video.py

**Comment by sunhaozhepy** [comment]
Ah OK they must have updated the repo not long ago.

However if I make an editable install from Diffusers, I get the following error when running `v2v.py`:

```
Traceback (most recent call last):
  File "/data/jupyter/diffusers_rerender/diffusers-Rerender/v2v.py", line 2, in <module>
    from diffusers import StableDiffusionRerenderPipeline
ImportError: cannot import name 'StableDiffusionRerenderPipeline' from 'diffusers' (/data/jupyter/diffusers_rerender/diffusers/src/diffusers/__init__.py)
```

Does this mean that I should install the Diffusers package embedding in [this repo](https://github.com/SingleZombie/diffusers-Rerender)? However there's no `rerender_a_video.py`, as far as I'm concerned.

**Comment by SingleZombie** [comment]
> I'm trying out the diffusers implementation of your project ([this repo](https://github.com/SingleZombie/diffusers-Rerender)). I see that I need to install gmflow in the root directory. I wonder how I should do that?

That repo is implemented on an old DIffusers version. Please follow the instructions in https://github.com/huggingface/diffusers/tree/main/examples/community#Rerender_A_Video to use it. "Install gmflow" means `git clone` it.

**Comment by sunhaozhepy** [comment]
OK I'll try that. Thank you for your help!
