### ISSUE TITLE
low gpu-util

### ISSUE THREAD

**Issue by SongYxing** [williamyang1991/Rerender_A_Video#129]
I run in the A100 80g bur the gpu-util is keeping lower than 20%. It makes the bad inference speed (60~80 second / frame).

**Comment by williamyang1991** [comment]
I suppose that's the ebsynth part (not fully GPU-based, mostly CPU-based).  Ebsynth is not implemented by us. If you are interested, you can improve the Ebsynth part to make a high gpu-util.

Our diffusion part does not have low gpu-util.

**Comment by SongYxing** [comment]
I am sorry. But (60~80 second / frame) infers to the ddim phase speed.

**Comment by williamyang1991** [comment]
But in my case, on V100 32G, the speed is much faster than your case. (512x512 videos, take about 14.23s per frame)
Did you use very large video resolution?

**Comment by SongYxing** [comment]
I also fixed the 512 x 512 resolution. And varm cost about 10g. 
In my case, we spend about 200s to load the model and inference per frame cost 60s. I first though it work in the CPU, but i check it work in CUDA:4 (I set it through torch.set.cuda). 
And it is difficulty to set gpu id in weiui.py. CUDA_VISIA... and os cmd are not working. It only work when i set it in front of the per process_x.

**Comment by williamyang1991** [comment]
I remember that I can set the GPU by CUDA_VISIBLE_DEVICES=0 python webUI.py.
The slow speed might also caused by WebUI? You can try to use [rerender.py](https://github.com/williamyang1991/Rerender_A_Video/blob/main/rerender.py) instead to test the speed.
If rerender.py is also slow, then I think there may be something wrong with your hardware or software.

**Comment by SongYxing** [comment]
rerender.py also performs bad. I test another rep (fresco)

**Comment by williamyang1991** [comment]
https://github.com/williamyang1991/Rerender_A_Video/blob/main/inference_playground.ipynb
You can see the recorded speed in my inference_playground.ipynb

![image](https://github.com/williamyang1991/Rerender_A_Video/assets/18130694/68d080f2-9323-4f6e-9aad-c0f2e831a94e)

**Comment by SongYxing** [comment]
thanks for your patient resp

**Comment by SongYxing** [comment]
this image shows the speed
![491714035079_ pic](https://github.com/williamyang1991/Rerender_A_Video/assets/69084724/bcf95b2c-0e6b-4920-ad8f-9a61db9aa03f)

**Comment by williamyang1991** [comment]
I cannot help you with it. I think it is not the problem of my code. 
Your hardware or software or setting or environment may have some problem that slow down the code.
