### ISSUE TITLE
How to NOT use the first frame, only use pre_result?

### ISSUE THREAD

**Issue by Tonniia** [williamyang1991/Rerender_A_Video#132]
Hi, I have tried set firstx0 as False, but the generated result seems as same as firstx0=True.

**Comment by williamyang1991** [comment]
I think the simplest way is adding 
```
        first_result = pre_result
        first_img = pre_img
```
after
https://github.com/williamyang1991/Rerender_A_Video/blob/dfaf9d8825f226a2f0a0b731ab2adc84a3f2ebd2/rerender.py#L373

**Comment by Tonniia** [comment]
Thanks. Indeed, anchor frame (j = 0) provides better guidance. However, when the motion between the first frame and current frame is large, the flow estimation will be difficult. In Fig3, Pixel-aware Fusion is only operated from pre_frame, however in line:
https://github.com/williamyang1991/Rerender_A_Video/blob/dfaf9d8825f226a2f0a0b731ab2adc84a3f2ebd2/rerender.py#L301
Pixel-aware Fusion also operated from the first frame.  
I use a video that the motion between the first frame and following frames is large (e.g. a car is moving, not like pexels-cottonbro that the motion between frames are equal). The occ_area will be large and repainted, lead to inconsistency:
![image](https://github.com/williamyang1991/Rerender_A_Video/assets/56153611/0f16320d-03b1-4f06-b7bb-b6b8fca78f1d)
![image](https://github.com/williamyang1991/Rerender_A_Video/assets/56153611/90f47348-1d92-4ddf-a3f9-b7aa4e6254fb)
occ_pre and occ_first:
![image](https://github.com/williamyang1991/Rerender_A_Video/assets/56153611/6b4dba7d-5b1d-43d3-bc4c-271ce5bde997)

https://github.com/williamyang1991/Rerender_A_Video/assets/56153611/f32a843b-0618-471a-99e0-d54c53a58206

I try to only Pixel-aware Fusion the pre_frame:
```
blend_results = (1 - blend_mask_pre
                             ) * warped_pre + blend_mask_pre * direct_result
# blend_results = (
#     1 - blend_mask_0) * warped_0 + blend_mask_0 * blend_results

# bwd_occ = 1 - torch.clamp(1 - bwd_occ_pre + 1 - bwd_occ_0, 0, 1)
bwd_occ = 1 - torch.clamp(1 - bwd_occ_pre, 0, 1)
```

but the inconsistency is much evident:


https://github.com/williamyang1991/Rerender_A_Video/assets/56153611/aa5920d5-b63c-4fb3-845c-72b499bc6671
