### ISSUE TITLE
Error accumulation (can see the image)

### ISSUE THREAD

**Issue by Sonia-kong** [williamyang1991/Rerender_A_Video#134]
Hi, much thanks to your excellent work. 
When I set key frame interval to 5, it seems that when the iteration reaches 221, there are large accumulated errors in the sky and trees. Do you know how to alleviate this symptom? @williamyang1991 
Thanks~
![0221](https://github.com/williamyang1991/Rerender_A_Video/assets/171914194/5a14130a-bd41-4b32-9d2d-c84f30b6d99a)

**Comment by williamyang1991** [comment]
Hope this could help you.
https://github.com/williamyang1991/Rerender_A_Video/issues/93#issuecomment-1766203905

**Comment by Sonia-kong** [comment]
get. thanks!
