### ISSUE TITLE
Source code issue

### ISSUE THREAD

**Issue by wangweiran970922** [williamyang1991/Rerender_A_Video#137]
No corresponding code locations were found, including Pipeline of the pixel aware latent fusion and Pipeline of the fidelity oriented image encoding.
Can you help locate it? Thank you very much

**Comment by williamyang1991** [comment]
Pipeline of the pixel aware latent fusion:
https://github.com/williamyang1991/Rerender_A_Video/blob/dfaf9d8825f226a2f0a0b731ab2adc84a3f2ebd2/rerender.py#L299-L346

and 
https://github.com/williamyang1991/Rerender_A_Video/blob/dfaf9d8825f226a2f0a0b731ab2adc84a3f2ebd2/src/ddim_v_hacked.py#L309-L323

---

Pipeline of the fidelity oriented image encoding:
https://github.com/williamyang1991/Rerender_A_Video/blob/dfaf9d8825f226a2f0a0b731ab2adc84a3f2ebd2/rerender.py#L309-L317
