### ISSUE TITLE
Is Ebsynth used in which parts?

### ISSUE THREAD

**Issue by FurkanGozukara** [williamyang1991/Rerender_A_Video#16]
I am trying to make a tutorial for this new release

Preparing an auto installer for windows

Installation of Ebsynth is really really hard

It requires specific visual studio version and adding cl.exe to path

Is it is necessary? In which part it is used?

Of course i can install but general public will have hard time

And which CUDA toolkit we need for it? Any version works?

```
G:\Rerender_A_Video auto install\Rerender_A_Video>python install2.py
Build Ebsynth Windows 64 bit. If you want to build for 32 bit, please modify install.py.
.\build-win64-cpu+cuda.bat
"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat"
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
ebsynth.cpp
The contents of <filesystem> are available only with C++17 or later.
ebsynth_cpu.cpp
ebsynth_cuda.cu
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\include\crt/host_config.h(160): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2019 (inclusive) are supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
FAILED
Failed to install Ebsynth.
```

**Comment by SingleZombie** [comment]
The Ebsynth is used in [video_blend.py](https://github.com/williamyang1991/Rerender_A_Video/blob/main/video_blend.py), which is called after rerender pipeline.https://github.com/williamyang1991/Rerender_A_Video/blob/10cb05bb942a62b10ad54a6d9ed55a5ea8bcb677/rerender.py#L465

Since we are not the developer of Ebsynth, we don't know how to improve the install script of Ebsynth. Maybe we can upload a pre-build Ebsyhth to skip the installation.

**Comment by FurkanGozukara** [comment]
> The Ebsynth is used in [video_blend.py](https://github.com/williamyang1991/Rerender_A_Video/blob/main/video_blend.py), which is called after rerender pipeline.
> 
> https://github.com/williamyang1991/Rerender_A_Video/blob/10cb05bb942a62b10ad54a6d9ed55a5ea8bcb677/rerender.py#L465
> 
> Since we are not the developer of Ebsynth, we don't know how to improve the install script of Ebsynth. Maybe we can upload a pre-build Ebsyhth to skip the installation.

thank you for reply

i managed to compile it but there are a lot more problems : https://github.com/williamyang1991/Rerender_A_Video/issues/18
