### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Meatfucker** [williamyang1991/Rerender_A_Video#17]
I ran the command `python .\rerender.py --input videos\video0.mov --output videos\lighty.mp4 --prompt "anime man"` and it began processing frames but then partway through it crashed with the following output.
`Global seed set to 59662
Data shape for DDIM sampling is (1, 4, 64, 112), eta 0.0
Running DDIM Sampling with 20 timesteps
DDIM Sampler: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:08<00:00,  2.39it/s]
Global seed set to 59662
Data shape for DDIM sampling is (1, 4, 64, 112), eta 0.0
Running DDIM Sampling with 20 timesteps
DDIM Sampler: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.51it/s]
Traceback (most recent call last):
  File ".\rerender.py", line 462, in <module>
    rerender(cfg, args.one, args.key_video_path)
  File ".\rerender.py", line 218, in rerender
    frame = cv2.imread(imgs[i + 1])
IndexError: list index out of range
(rerender) PS D:\ml\apps\Rerender_A_Video>`

**Comment by Meatfucker** [comment]
Using a mp4 instead of mov as the source video seems to have solved this.

**Comment by SingleZombie** [comment]
I guess the program failed on frame index proprocessing. We will fix the bug in the future. Now please manually set the `frame_count` in the config file and make sure it mods `interval` equals 2. For example, you want process the first 100 frames of the video and the keyframe interval is 10, then set `frame_count` to `102`.
