### ISSUE TITLE
After launching the web UI, it throws an error

### ISSUE THREAD

**Issue by AbramovS1** [williamyang1991/Rerender_A_Video#20]
H:\Rerender_A_Video>python webUI.py
Traceback (most recent call last):
  File "H:\Rerender_A_Video\webUI.py", line 18, in <module>
    import src.import_util  # noqa: F401
  File "H:\Rerender_A_Video\src\import_util.py", line 10, in <module>
    import deps.ControlNet.share  # noqa: F401 E402
ModuleNotFoundError: No module named 'deps.ControlNet.share'

**Comment by SingleZombie** [comment]
Please add `--recursive` to your `git clone` command to install the submodules. If you forget it, you can enter `git submodule update --init --recursive` to do the same thing.

**Comment by AbramovS1** [comment]
It always gives this error

H:\Rerender_A_Video>git clone --recursive git@github.com:williamyang1991/Rerender_A_Video.git
Cloning into 'Rerender_A_Video'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by SingleZombie** [comment]
Maybe you should set the SSH key for your GitHub account. Please refer to this link: https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account

**Comment by AbramovS1** [comment]
Everything seems to be installed and everything is step-by-step, but it still gives this error!

logging improved.
Traceback (most recent call last):
  File "H:\Rerender_A_Video\Rerender_A_Video\webUI.py", line 24, in <module>
    from flow.flow_utils import get_warped_and_mask
  File "H:\Rerender_A_Video\Rerender_A_Video\flow\flow_utils.py", line 209, in <module>
    flow_calc = FlowCalc()
  File "H:\Rerender_A_Video\Rerender_A_Video\flow\flow_utils.py", line 155, in __init__
    checkpoint = torch.load(model_path,
  File "C:\Users\mrjek\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\mrjek\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\mrjek\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './models/gmflow_sintel-0c07dcb3.pth'

**Comment by FurkanGozukara** [comment]
recursive clone not working
i had to clone each repo manually

**Comment by williamyang1991** [comment]
> Everything seems to be installed and everything is step-by-step, but it still gives this error!
> 
> logging improved. Traceback (most recent call last): File "H:\Rerender_A_Video\Rerender_A_Video\webUI.py", line 24, in from flow.flow_utils import get_warped_and_mask File "H:\Rerender_A_Video\Rerender_A_Video\flow\flow_utils.py", line 209, in flow_calc = FlowCalc() File "H:\Rerender_A_Video\Rerender_A_Video\flow\flow_utils.py", line 155, in **init** checkpoint = torch.load(model_path, File "C:\Users\mrjek\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 791, in load with _open_file_like(f, 'rb') as opened_file: File "C:\Users\mrjek\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 271, in _open_file_like return _open_file(name_or_buffer, mode) File "C:\Users\mrjek\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 252, in **init** super().**init**(open(name, mode)) FileNotFoundError: [Errno 2] No such file or directory: './models/gmflow_sintel-0c07dcb3.pth'

running 
```
python install.py
```
will download gmflow_sintel-0c07dcb3.pth to `models`

https://github.com/williamyang1991/Rerender_A_Video/blob/7f8072f464557fc7fcb2eb5e3daaa2456b03ac8a/install.py#L75

**Comment by williamyang1991** [comment]
> recursive clone not working i had to clone each repo manually

@SingleZombie This seems a common issue. Can we do something to make recursive clone work?

**Comment by nathanshipley** [comment]
On Linux, I was able to get it recursively clone by modifying the .gitignore file to change 
`url = git@github.com:haofeixu/gmflow.git` 
so it looks like this:

```
[submodule "deps/gmflow"]
	path = deps/gmflow
	url = https://github.com/haofeixu/gmflow.git
[submodule "deps/ControlNet"]
	path = deps/ControlNet
	url = https://github.com/lllyasviel/ControlNet.git
[submodule "deps/ebsynth"]
	path = deps/ebsynth
	url = https://github.com/SingleZombie/ebsynth.git
```

Then run:

```
git submodule sync
git submodule update --init --recursive
```

Then make sure your environment is set up properly (I just made a new one from the .yml file), activate it, then run `python install.py` which builds and downloads things.

Then, I also needed to upgrade gradio to avoid the `KeyError: 'dataset'` error using: 
`pip install gradio==3.44.3`

Finally, to get the Greek sculpture example to work, I needed to change the Base model under `Advanced options for the 1st frame translation` to `Stable Diffusion 1.5` or download and properly link another base model as described in the readme.
