### ISSUE TITLE
Released an auto installer hopefully a full public tutorial coming soon

### ISSUE THREAD

**Issue by FurkanGozukara** [williamyang1991/Rerender_A_Video#25]
https://github.com/williamyang1991/Rerender_A_Video/assets/19240467/d7f04930-5af7-4707-a6ed-60725fa221aa

1 click Auto installer : https://www.patreon.com/posts/1-click-auto-for-89457537

Auto installer made for Windows. You only need to have Python and Git installed. Instructions are shared

Hopefully a free public full tutorial coming soon on SECourses stay subscribed > https://www.youtube.com/SECourses

Twitter sharing : https://twitter.com/GozukaraFurkan/status/1703797121126662602

Source repo : https://github.com/williamyang1991/Rerender_A_Video

Just uploaded original video to web ui : https://twitter.com/RishiSunak/status/1702630698178236756

Used default settings, flat2DAnimerge_v30 model and just a man in a room prompt

For audio I used ffmpeg to copy it from original source to output

Spent more than 2 days to prepare installer because there were a lot of bugs and errors that I had to debug and figure out fix

![image](https://github.com/williamyang1991/Rerender_A_Video/assets/19240467/0c13d7a4-0e18-4940-bc1b-2c5f17178568)

![image](https://github.com/williamyang1991/Rerender_A_Video/assets/19240467/b946f62b-15a3-48d7-84c3-46d505f9114c)

**Comment by 831Digital** [comment]
I think someone might be selling your autoinstaller on reddit.

**Comment by FurkanGozukara** [comment]
> I think someone might be selling your autoinstaller on reddit.

wow where?

**Comment by pondloso** [comment]
I love your work and would like some simple guide to install it in vastai or runpod.

**Comment by FurkanGozukara** [comment]
> I love your work and would like some simple guide to install it in vastai or runpod.

hopefully will make a tutorial for windows and runpod - free publicly shared on youtube

i can release auto installer for runpod on Patreon earlier if you are interested in

**Comment by Foul-Tarnished** [comment]
why don't you just do a python virtual environment somewhere, where user choose ?

**Comment by FurkanGozukara** [comment]
> why don't you just do a python virtual environment somewhere, where user choose ?

my script doing that

generates a venv and install inside it wherever the folder you choose
