### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by BryanHarrisScripts** [williamyang1991/Rerender_A_Video#27]
Thank you for sharing. I have this up and running but would like some help to obtain a desirable image. Example: if I want a cartoon character, what parameters do I need to set? Just some basics, please and thank you.

**Comment by williamyang1991** [comment]
Thank you for your interest!

1. Find a cartoon model, like https://civitai.com/models/35960/flat-2d-animerge, and add it to the webUI by modifying sd_model_cfg.py to add paths to the saved SD models

2. using key word like `cartoon` in the prompt.

3. generally follow the setting of https://github.com/williamyang1991/Rerender_A_Video/blob/main/config/woman.json

4. tune the parameters according to the advanced options in README.MD

![image](https://github.com/williamyang1991/Rerender_A_Video/assets/18130694/126e1176-b13d-481e-9ae4-c3c715cb094c)

**Comment by BryanHarrisScripts** [comment]
Thank you! That worked... just curious what other models can I download and configure. And I'm probably not prompting correctly for the models but cannot find documentation.

**Comment by williamyang1991** [comment]
You can find models in [huggingface](https://huggingface.co/models?sort=trending&search=stable+diffusion) and [civitai](https://civitai.com/models)

prompt is usually a sentence describing the content in your input video + some words about `styles`  like `in cartoon style`, `yellow hair`, `cute`, etc.
