### ISSUE TITLE
What is GPU usage of Rerender_A_Video?

### ISSUE THREAD

**Issue by ninjasaid2k** [williamyang1991/Rerender_A_Video#37]
What is the GPU utilization of the process 'Rerender_A_Video'? Does it demand a substantial amount of VRAM, or is it sufficiently efficient for utilization on consumer-grade computers?

**Comment by williamyang1991** [comment]
24GB VRAM is required. Please refer to https://github.com/williamyang1991/Rerender_A_Video/pull/23#issue-1900789461 to reduce memory consumption.
