### ISSUE TITLE
How about using lora to do video style changes?please enlighten me

### ISSUE THREAD

**Issue by tbxmh** [williamyang1991/Rerender_A_Video#39]

**Comment by williamyang1991** [comment]
Our method is based on the original SD model. 
You may need to [merge](https://github.com/huggingface/diffusers/blob/main/scripts/convert_lora_safetensor_to_diffusers.py) LoRA into Diffuser models.
And then, you may need to [convert](https://github.com/huggingface/diffusers/blob/main/scripts/convert_diffusers_to_original_stable_diffusion.py) Diffuser models to the original one.

Then our method can load this new model. 
You can just modify `sd_model_cfg.py` to add paths to the saved merged SD models to load it.

**Comment by tbxmh** [comment]
Thank you for your reply. May I ask if you have used xformer to speed up reasoning? I have noticed that the speed of this excellent work seems to be a bit slow. Or do you have any other ways to speed up reasoning?

**Comment by williamyang1991** [comment]
We didn't tested our code with xformer to speed up. 
But some users have successfully use it in https://github.com/williamyang1991/Rerender_A_Video/pull/23#issue-1900789461

**Comment by williamyang1991** [comment]
And we are implementing our method in Diffusers, which might be more efficient.

**Comment by tbxmh** [comment]
Thank you for your reply.Looking forward to your further work！

**Comment by zhanghongyong123456** [comment]
> Our method is based on the original SD model. You may need to [merge](https://github.com/huggingface/diffusers/blob/main/scripts/convert_lora_safetensor_to_diffusers.py) LoRA into Diffuser models. And then, you may need to [convert](https://github.com/huggingface/diffusers/blob/main/scripts/convert_diffusers_to_original_stable_diffusion.py) Diffuser models to the original one.
> 
> Then our method can load this new model. You can just modify `sd_model_cfg.py` to add paths to the saved merged SD models to load it.

大佬，请问如何基于 embedding  进行风格化呢，有相关的融合示例吗

**Comment by williamyang1991** [comment]
是text embedding吗？
你在
https://civitai.com/models
上找embedding的模型，然后prompt里用对应的Trigger Words

我没用过，所以具体细节我也不清楚。

**Comment by zhanghongyong123456** [comment]
> 是text embedding吗？ 你在 https://civitai.com/models 上找embedding的模型，然后prompt里用对应的Trigger Words
> 
> 我没用过，所以具体细节我也不清楚。

https://civitai.com/models/9416?modelVersionId=11173  我看到这个风格很强，所以想测试一下  ，他不可以像Lora 一样融合到模型里吗

**Comment by williamyang1991** [comment]
这种看上去是用的直接把text embedding用到base model （base model可以加上其他LoRA）上了。
具体还需要你自己研究一下

**Comment by zhanghongyong123456** [comment]
> 这种看上去是用的直接把text embedding用到base model （base model可以加上其他LoRA）上了。 具体还需要你自己研究一下
我看了原始论文代码，加载.pt采用DDPM 中  LatentDiffusion 类，但我找不到我们基础模型采用什么加载的？
![QQ图片20230926153845](https://github.com/williamyang1991/Rerender_A_Video/assets/48466610/9ba20618-c807-4963-aaae-0fd91dbfd882)
![QQ图片20230926153832](https://github.com/williamyang1991/Rerender_A_Video/assets/48466610/f47c8082-8f55-429b-b002-fcbff9f46bc3)

**Comment by williamyang1991** [comment]
基础模型就是原版的stable diffusion 1.5模型+controlnet（`models/control_sd15_canny.pth`），
也应该可以加LoRA

这部分具体代码是controlnet里的，其中对应LatentDiffusion 类的应该是，具体需要你研究一下controlnet的代码
`diffusion_model = self.model.diffusion_model`

https://github.com/lllyasviel/ControlNet/blob/d3284fcd0972c510635a4f5abe2eeb71dc0de524/cldm/cldm.py#L330

**Comment by zhanghongyong123456** [comment]
> 基础模型就是原版的stable diffusion 1.5模型+controlnet（`models/control_sd15_canny.pth`）， 也应该可以加LoRA
> 
> 这部分具体代码是controlnet里的，其中对应LatentDiffusion 类的应该是，具体需要你研究一下controlnet的代码 `diffusion_model = self.model.diffusion_model`
> 
> https://github.com/lllyasviel/ControlNet/blob/d3284fcd0972c510635a4f5abe2eeb71dc0de524/cldm/cldm.py#L330

当我增加embedding  模型加载，出现没有属性error，我对比 embedding 源码  和  controlnet 代码里面的ddpm，发现少一部分 embedding 相关代码，我不确定是  diffusion 版本问题还是  embedding   源码特有的
 
![4](https://github.com/williamyang1991/Rerender_A_Video/assets/48466610/77bb3bd9-b03b-4190-b558-001ceeef9e22)
![01](https://github.com/williamyang1991/Rerender_A_Video/assets/48466610/fae03d2f-6a88-444f-b49f-663335e111b6)

![1](https://github.com/williamyang1991/Rerender_A_Video/assets/48466610/28806a9b-7379-4695-a19b-7e1a8cf99a2e)
![3](https://github.com/williamyang1991/Rerender_A_Video/assets/48466610/32181324-447b-4af5-8a57-5b4157d914bf)

**Comment by williamyang1991** [comment]
self.control_model 是 controlnet，是stable diffusion的旁路

self.model.diffusion_model 才是 stable diffusion 本体，才是LatentDiffusion model

**Comment by zhanghongyong123456** [comment]
> self.control_model 是 controlnet，是stable diffusion的旁路
> 
> self.model.diffusion_model 才是 stable diffusion 本体，才是LatentDiffusion model

  我尝试了在   self.model.diffusion_model  添加   embedding，但是  出现另一个类的错误，我看到他的父类 和LatentDiffusion model 没一点关系，才换的这个位置添加
![image](https://github.com/williamyang1991/Rerender_A_Video/assets/48466610/5b02b2cb-c7f7-4dfb-a8bf-c1ccc9650521)

![image](https://github.com/williamyang1991/Rerender_A_Video/assets/48466610/936ad937-386f-4bcd-aebe-6383ece71547)

**Comment by williamyang1991** [comment]
我看了一下，你的是texture inversion的代码，是基于LDM修改的代码，
ControlNet的代码也是基于LDM修改的代码，
LDM是没有你说的embedding相关的函数的，所以这部分是texture inversion自己修改的代码。
那你需要做的是把texture inversion修改的部分看懂并迁移到ControlNet的代码中，

但这已经超出了我这个项目的范围，所以后面我就不再继续解答相关问题，这个issue也已经讨论和lora无关的问题很久了。

**Comment by zhanghongyong123456** [comment]
> 我看了一下，你的是texture inversion的代码，是基于LDM修改的代码， ControlNet的代码也是基于LDM修改的代码， LDM是没有你说的embedding相关的函数的，所以这部分是texture inversion自己修改的代码。 那你需要做的是把texture inversion修改的部分看懂并迁移到ControlNet的代码中，
> 
> 但这已经超出了我这个项目的范围，所以后面我就不再继续解答相关问题，这个issue也已经讨论和lora无关的问题很久了。

好的，我在查一下其他相关实现代码，看看有没有解决办法，谢谢您的解答

**Comment by justinjohn0306** [comment]
@zhanghongyong123456 had any luck with it?
