### ISSUE TITLE
Missing  control_sd15_hed.pth

### ISSUE THREAD

**Issue by samxoo** [williamyang1991/Rerender_A_Video#40]
Hello, after few nightmares, I figured out that  after instalation, that file were missing, only control_sd15_canny.pth exist.

Here is how to fix it : 

if you have an issue control_sd15_hed.pth not found, you could download it from : https://huggingface.co/lllyasviel/ControlNet/blob/main/models/control_sd15_hed.pth

**Comment by SingleZombie** [comment]
Yes. We only install ControlNet Canny in the script. If you want other ControlNet model, you may install them on your own.

**Comment by williamyang1991** [comment]
@samxoo You can uncomment this line to download HED

https://github.com/williamyang1991/Rerender_A_Video/blob/53a50831aeecc873acdd3b69e16c2e8e4dfeefb2/install.py#L77

We comment it our just to save the installation time to void downloading many huge pretrained models.

**Comment by williamyang1991** [comment]
To make life easier, we have made the line uncommented by default.

**Comment by samxoo** [comment]
I gotcha! Thanks a lot, another quick question! 
I just cloned  Huggingface space now, but getting  KeyError: 'dataset' error when trying to run  1st key frame, is there a way to upgrade Gradio there?

**Comment by samxoo** [comment]
> To make life easier, we have made the line uncommented by default.

Thanks a lot! 
Another quick question, I am running 4 second video  Run Key Frames by default settings, it already took  116 Minutes,  on GTX 3060 12 GB, CPU i9 9900KF, is this normal? it's still not finished
![image](https://github.com/williamyang1991/Rerender_A_Video/assets/18744131/a7e8318e-74dd-4272-960e-9361b817c16e)

**Comment by williamyang1991** [comment]
Usually, each key frame, it take me about 10-20 second on a V100 GPU.
In your case, each key frame takes 15 mins.
I think this is the reason your program takes a lot of time.

You can check the folder whether the generated key frames are normal. If it looks correct, then it is normal, and the slow speed may due to your system setting or GPU.

**Comment by samxoo** [comment]
> Usually, each key frame, it take me about 10-20 second on a V100 GPU. In your case, each key frame takes 15 mins. I think this is the reason your program takes a lot of time.
> 
> You can check the folder whether the generated key frames are normal. If it looks correct, then it is normal, and the slow speed may due to your system setting or GPU.

Thanks for your quick repsonse!


So I just checked Rerender_A_Video\result\06256\keys  and there is only 3 Frame generated 0001.png, 0011.png, 0021.png (idk why it skips the numbers in name) when  \Rerender_A_Video\result\06256\video  have 277 Frame (original video frames ) 


I am running Stable Difussion Automatic1111 without issues, its way more faster to generate 1 frame picture there, it takes like 5 sec max
