### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by PeanutArthur** [williamyang1991/Rerender_A_Video#48]
Hello,I start webui sucessfully,and install all models,but I got some RuntimeERROR.
Maybe someone know how to solve the problem.
: ）

` File "C:\Users\PeanutArthur\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 282, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory`

<img width="854" alt="屏幕截图 2023-09-25 174115" src="https://github.com/williamyang1991/Rerender_A_Video/assets/86914064/e80a0982-7705-4026-bf76-969f099cadfd">

**Comment by williamyang1991** [comment]
According to https://stackoverflow.com/questions/71617570/pytorchstreamreader-failed-reading-zip-archive-failed-finding-central-directory,
the model `models/control_sd15_canny.pth` seems not downloaded completely.
You can manually download it from https://huggingface.co/lllyasviel/ControlNet/''resolve/main/models/control_sd15_canny.pth

**Comment by PeanutArthur** [comment]
> According to https://stackoverflow.com/questions/71617570/pytorchstreamreader-failed-reading-zip-archive-failed-finding-central-directory, the model `models/control_sd15_canny.pth` seems not downloaded completely. You can manually download it from https://huggingface.co/lllyasviel/ControlNet/''resolve/main/models/control_sd15_canny.pth

THANKS!
It does work. : )
But the link is broken,someone can manually download from 
https://huggingface.co/lllyasviel/ControlNet/tree/main/models
