### ISSUE TITLE
 Can't load tokenizer for 'openai/clip-vit-large-patch14

### ISSUE THREAD

**Issue by capoz1o** [williamyang1991/Rerender_A_Video#49]
Hello,I start webui sucessfully,and install all models,but I got some RuntimeERROR.
please help me，thank u！ verymuch

<img width="936" alt="Snipaste_2023-09-25_18-09-30" src="https://github.com/williamyang1991/Rerender_A_Video/assets/94856524/5dba2dbc-b856-45d1-b900-8cda671c8f22">

**Comment by 1414521825** [comment]
I have download the needed files(all) [huggingface](https://huggingface.co/openai/clip-vit-large-patch14/tree/main) and change the url
![image](https://github.com/williamyang1991/Rerender_A_Video/assets/74236255/62135127-4ced-43e8-bb45-e517bbca09e9)

**Comment by basakamars** [comment]
> 我已经下载了所需的文件（全部）[拥抱脸](https://huggingface.co/openai/clip-vit-large-patch14/tree/main)并更改了网址 ![图像](https://user-images.githubusercontent.com/74236255/273799765-62135127-4ced-43e8-bb45-e517bbca09e9.png)

Which file is this code in

**Comment by zhaoxin111** [comment]
![image](https://github.com/williamyang1991/Rerender_A_Video/assets/9295202/9eb65626-0f64-4fd3-9f40-203a9c2122b6)
which file should be download?

**Comment by 1414521825** [comment]
![image](https://github.com/williamyang1991/Rerender_A_Video/assets/74236255/f0da40d7-ec0c-4b1f-89ed-d69bd1f281fd)
in this file
