### ISSUE TITLE
Is SDXL supported ? 

### ISSUE THREAD

**Issue by koshimazaki** [williamyang1991/Rerender_A_Video#50]
I cant find the mention of SDXL. Is it supported and if not are you planning adding that compatibility ? 
Thanks!

**Comment by williamyang1991** [comment]
Unfortunately, SDXL is not released when we developed this code. So our code needs modification to support SDXL.
We currently don't have plan to do that. But we are welcome that if other users would like to do that.

**Comment by koshimazaki** [comment]
Thank you
