### ISSUE TITLE
is it possible to run on Mac M2  chip ?

### ISSUE THREAD

**Issue by alyfreym** [williamyang1991/Rerender_A_Video#55]
is it possible to run on Mac M2  chip ? Or some components run only on Nvidia/CUDA technology?

**Comment by williamyang1991** [comment]
I've never used a Mac, so I have no idea.
The diffusion part is simply based on ControlNet. So if it can be run on Mac, then our diffusion part can.
The Ebsyth part is not developed by us. So I'm not sure whether it can be run on Mac.

**Comment by Trentonom0r3** [comment]
Mac can only run CPU for ebsynth, and M1/M2 aren't supported. 
At least that's the only build option you have with the original source code.
see: 
https://github.com/Trentonom0r3/Ezsynth/issues/6#issue-1912586793
