### ISSUE TITLE
Unexpected artifacts of video_blender.py

### ISSUE THREAD

**Issue by Jeff-LiangF** [williamyang1991/Rerender_A_Video#68]
Hi @williamyang1991 ,

Thanks for your impressive work! I am trying to use your` video_blender.py` to interpolate my own video. The following is my command

`python video_blend.py '$dir' --itv 2 --key 'keys' --output '$folder_path/$subfolder_name.mp4' --fps 25.0 -ps --beg 0 --end 2`

However, sometimes, it generates very weird artifacts. For [my example](https://drive.google.com/drive/u/0/folders/1_YAFWYt7Ey9D9OtjjwtQNO7YpNGw8Ct4), I have three source images 0000.png, 0001.png and 0002.png, two already edited key frames: key_0000.png and key_0002.png. I use the aforementioned script the generate the gen_0001.png. However, there are some unexpected artifacts around the shoulder of the man. I was wondering if you have encountered this kind of artifacts during your experiments. If yes, do you have solutions?

Experimental images can be downloaded [here](https://drive.google.com/drive/u/0/folders/1_YAFWYt7Ey9D9OtjjwtQNO7YpNGw8Ct4). Thank you!

**Comment by Jeff-LiangF** [comment]
One more note: I've also tried the official [Ebsythn app](https://ebsynth.com/) with my [my example](https://drive.google.com/drive/u/0/folders/1_YAFWYt7Ey9D9OtjjwtQNO7YpNGw8Ct4). It turns out they didn't have such problem.

**Comment by williamyang1991** [comment]
Thank you!
@SingleZombie We will look into this example to see if there are bugs.

**Comment by SingleZombie** [comment]
I know where the bug is. In the following codes, we inpaint the occluded area due to the flow warp. However, in this case, the black shirt is incorrectly recognized as occluded area.  You can comment line 103~109 to avoid the bug in this case, but it may cause black artifacts in other case. We need to add more processing to completely address the bug. I will upload a PR 
```python
https://github.com/williamyang1991/Rerender_A_Video/blob/21ed9489eb6249fc9a67721478fd4c6f128f85a7/blender/guide.py#L109
```

**Comment by Jeff-LiangF** [comment]
HI @SingleZombie ,

Thanks for getting back to me. It looks like if the optical flow is inaccurate, there may be more artifacts due to the incorrect occluded areas by flow warp. Am I right?

**Comment by SingleZombie** [comment]
> HI @SingleZombie ,
> 
> Thanks for getting back to me. It looks like if the optical flow is inaccurate, there may be more artifacts due to the incorrect occluded areas by flow warp. Am I right?

Yes, inaccurate optical flow may cause artifacts. However, this bug is due to the incorrect occluded mask which is obtained from color threshold rather than forward and backward flow. Now we use correct occluded masks from optical flow.
