### ISSUE TITLE
How to add other ControlNets like Lineart_anime?

### ISSUE THREAD

**Issue by tjohn88** [williamyang1991/Rerender_A_Video#69]
Hi!
It's not so clear how to add Lineart_anime or Depth_leres++ to WebUI.py.
This is a code should be changed:
"elif control_type == 'canny':
            canny_detector = CannyDetector()"

In your example, you add:
"from ControlNet.annotator.midas import MidasDetector
...
elif control_type == 'depth':
--
173 | +             midas = MidasDetector()
174 | +
175 | +             def apply_midas(x):
176 | +                 detected_map, _ = midas(x)
177 | +                 return detected_map
178 | +
179 | +             self.detector = apply_midas
"
But how can we add some new ControlNet.annotators like a Lineart? 
I compared the annotators code in my Automatic1111 build.
There is no such obvious class creation for Leres++ and Lineart as **"class MidasDetector:"** for Midas 
(I mean the files "sd-webui-controlnet\annotator\lineart_anime\ __init__.py").

Or is there another way, easier?

**Comment by YuzhiChen001** [comment]
have you solved it？

**Comment by williamyang1991** [comment]
Maybe you need to check the official controlnet project.
I find it uses a pretrained network of `LineartAnimeDetector`. 
https://github.com/lllyasviel/ControlNet-v1-1-nightly/blob/main/annotator/lineart_anime/__init__.py

And do something like 
```python
    if det == 'Lineart_Anime':
        if not isinstance(preprocessor, LineartAnimeDetector):
            preprocessor = LineartAnimeDetector()

    with torch.no_grad():
        input_image = HWC3(input_image)

        if det == 'None':
            detected_map = input_image.copy()
        else:
            detected_map = preprocessor(resize_image(input_image, detect_resolution))
            detected_map = HWC3(detected_map)
```
https://github.com/lllyasviel/ControlNet-v1-1-nightly/blob/e2b44154b72965c5e11b1ccee941d550682e4701/gradio_lineart_anime.py#L36-L47
