### ISSUE TITLE
webui pause or interrupt

### ISSUE THREAD

**Issue by YuzhiChen001** [williamyang1991/Rerender_A_Video#74]
参数众多，经常需要中断，重跑。我没有在webui找到暂停或者终止的按钮，希望作者能提示一下位置或者加上该功能。祝生活愉快，工作顺利。

**Comment by williamyang1991** [comment]
这个wbui基于Gradio，但是Gradio似乎没有提供暂停或者终止的功能。
我自己一般是用notebook调关键帧的参数，可以随时暂停或者终止。
https://github.com/williamyang1991/Rerender_A_Video/blob/main/inference_playground.ipynb

**Comment by YuzhiChen001** [comment]
Thanks！
