### ISSUE TITLE
!python install.py src/ebsynth.cpp:12:10: fatal error: filesystem: No such file or directory

### ISSUE THREAD

**Issue by dakuohaozyj** [williamyang1991/Rerender_A_Video#75]
bash build-linux-cpu+cuda.sh
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
src/ebsynth.cpp:12:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
Failed to install Ebsynth.

Hope this can help solve the problem. Thanks
![image](https://github.com/williamyang1991/Rerender_A_Video/assets/136295745/a5665d08-c4de-47a0-8064-e963f5319d9e)
![image](https://github.com/williamyang1991/Rerender_A_Video/assets/136295745/535e1070-d010-4ab9-a90a-8817cb190814)

**Comment by dakuohaozyj** [comment]
![image](https://github.com/williamyang1991/Rerender_A_Video/assets/136295745/c7130753-d94e-4123-931e-2d749de14cd7)

**Comment by williamyang1991** [comment]
I just find solutions via google

https://stackoverflow.com/questions/39231363/fatal-error-filesystem-no-such-file-or-directory
https://stackoverflow.com/questions/63076851/filesystem-not-found
https://stackoverflow.com/questions/42633477/macos-clang-c17-filesystem-header-not-found
