### ISSUE TITLE
No module 'xformers'. Proceeding without it

### ISSUE THREAD

**Issue by dakuohaozyj** [williamyang1991/Rerender_A_Video#76]
No module 'xformers'. Proceeding without it  hope your reply
![image](https://github.com/williamyang1991/Rerender_A_Video/assets/136295745/2e1bfb66-57b6-4af3-9270-56f7528f64d1)

**Comment by williamyang1991** [comment]
No module 'xformers' is not an error, it's a warning. I can run without it.
You error is the EOFError, which means  your pickle file is empty (0 Bytes). You need to check the size of your pickle file first. 

You need to check model_path `./models/gmflow_sintel-0c07dcb3.pth`
Have you successfully downloaded the model?
You can download it through https://github.com/williamyang1991/Rerender_A_Video/blob/fcb7431fa042a64a8f96d1967b479047c3c2f84c/install.py#L50-L53
Or manually download it.

**Comment by dakuohaozyj** [comment]
> No module 'xformers' is not an error, it's a warning. I can run without it. You error is the EOFError, which means your pickle file is empty (0 Bytes). You need to check the size of your pickle file first.
> 
> You need to check model_path `./models/gmflow_sintel-0c07dcb3.pth` Have you successfully downloaded the model? You can download it through
> 
> https://github.com/williamyang1991/Rerender_A_Video/blob/fcb7431fa042a64a8f96d1967b479047c3c2f84c/install.py#L50-L53
> 
> 
> Or manually download it.

OK I'll try

**Comment by dakuohaozyj** [comment]
!pip install xformers==0.0.16 Installing xformer model，Already manually downloaded gmflow_sintel-0c07dcb3.pth and placed it in the specified location，
![image](https://github.com/williamyang1991/Rerender_A_Video/assets/136295745/d8f6aaae-ac33-4c2b-955f-a9005572b3c8)
The new question is do you want to download more content?
