### ISSUE TITLE
What model was used for the anime results?

### ISSUE THREAD

**Issue by vedantroy** [williamyang1991/Rerender_A_Video#92]
For this result:
![image](https://github.com/williamyang1991/Rerender_A_Video/assets/8407819/82693851-53fb-4cdc-9b29-bbba9707c67b)

What custom model was used?

**Comment by williamyang1991** [comment]
https://civitai.com/models/6526/studio-ghibli-style-lora

**Comment by vedantroy** [comment]
Thanks for the quick response -- how did you manage to load this LoRA into your method?
Did you use the method mentioned here: https://github.com/williamyang1991/Rerender_A_Video/issues/39#issuecomment-1730678296?

**Comment by williamyang1991** [comment]
> Did you use the method mentioned here: #39 

Yes

> the controlnet weight + prompts you used for this example?

base model: [Counterfeit](https://civitai.com/models/4468?modelVersionId=7425)
lora model: [Ghibli](https://civitai.com/models/6526/studio-ghibli-style-lora)
prompt: "ghibli style, a handsome man"
contronet strength: 0.7
denoising strength: 0.25

**Comment by zoeouyang2543** [comment]
hello：
For this result:
1、a cartoon tiger
2、a traditional mountain in chinese ink wash painting
3、Hermione Granger 
What custom model was used?
do you mind posting the controlnet weight + prompts you used for this example?

**Comment by williamyang1991** [comment]
> hello： For this result: 1、a cartoon tiger 2、a traditional mountain in chinese ink wash painting 3、Hermione Granger What custom model was used? do you mind posting the controlnet weight + prompts you used for this example?

Please refer to https://drive.google.com/file/d/1HkxG5eiLM_TQbbMZYOwjDbd5gWisOy4m/view?usp=sharing

![image](https://github.com/williamyang1991/Rerender_A_Video/assets/18130694/5bcd56d2-a4f8-4e1b-b272-86c7a6c8efc2)

**Comment by zoeouyang2543** [comment]
I had met this error when i operated:python ./Rerender_A_Video/webUI.py

(base) oppoer@task-20240522083402-76752:/home/notebook/data/group/$ python ./Rerender_A_Video/webUI.py
logging improved.
Enabled sliced_attention.
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7860, 0, 0): cannot assign requested address
IMPORTANT: You are using gradio version 3.44.4, however version 4.29.0 is available, please upgrade.
--------
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7861, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7862, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7863, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7864, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7865, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7866, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7867, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7868, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7869, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7870, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7871, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7872, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7873, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7874, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7875, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7876, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7877, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7878, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7879, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7880, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7881, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7882, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7883, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7884, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7885, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7886, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7887, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7888, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7889, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7890, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7891, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7892, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7893, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7894, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7895, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7896, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7897, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7898, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7899, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7900, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7901, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7902, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7903, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7904, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7905, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7906, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7907, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7908, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7909, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7910, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7911, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7912, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7913, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7914, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7915, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7916, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7917, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7918, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7919, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7920, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7921, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7922, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7923, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7924, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7925, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7926, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7927, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7928, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7929, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7930, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7931, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7932, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7933, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7934, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7935, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7936, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7937, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7938, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7939, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7940, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7941, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7942, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7943, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7944, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7945, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7946, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7947, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7948, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7949, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7950, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7951, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7952, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7953, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7954, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7955, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7956, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7957, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7958, 0, 0): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 7959, 0, 0): cannot assign requested address
Traceback (most recent call last):
  File "/home/notebook/data/group/oyp/./Rerender_A_Video/webUI.py", line 969, in <module>
    block.launch(server_name='localhost')
  File "/home/oppoer/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1907, in launch
    ) = networking.start_server(
  File "/home/oppoer/.local/lib/python3.10/site-packages/gradio/networking.py", line 207, in start_server
    raise OSError(
OSError: Cannot find empty port in range: 7860-7959. You can specify a different port by setting the GRADIO_SERVER_PORT environment variable or passing the `server_port` parameter to `launch()`.

help!

**Comment by zoeouyang2543** [comment]
hello：
我把c站上的模型和lora转换成diffusers可以读的形式：
python ./diffusers-0.20.2/scripts/convert_original_stable_diffusion_to_diffusers.py --checkpoint_path ./Rerender_A_Video/models/counterfeitV30_v30.safetensors --dump_path ./Rerender_A_Video/models/Counterfeit --from_safetensors
python ./diffusers-0.20.2/scripts/convert_lora_safetensor_to_diffusers.py --base_model_path ./stable-diffusion-v1-5/ --checkpoint_path  ./Rerender_A_Video/models/moxin.safetensors --dump_path ./Rerender_A_Video/models/moxin
然后在用这个方案进行加载 python ./Rerender_A_Video/rerender.py --cfg ./Rerender_A_Video/config/real2sculpture.json，
得到的结果不是项目中给出来的效果，难道只能用weiui才能复现你给的效果吗？麻烦解答一下
real2sculpture.json的内容是：
{
    "input": "./Rerender_A_Video/videos/pexels_antoni_shkraba_8048492_540x960_25fps.mp4",
    "output": "./Rerender_A_Video/videos/man/blend.mp4",
    "work_dir": "./Rerender_A_Video/videos/man",
    "key_subdir": "keys",
    "sd_model": "./Rerender_A_Video/models/countfeit_ghibli",
    "frame_count": 102,
    "interval": 10,
    "crop": [
        0,
        180,
        0,
        0
    ],
    "prompt": "ghibli style, a handsome man",
    "a_prompt": "RAW photo, subject, (high detailed skin:1.2), 8k uhd, dslr, soft lighting, high quality, film grain, Fujifilm XT3",
    "n_prompt": "(deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers:1.4), (deformed, distorted, disfigured:1.3), poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, amputation",
    "x0_strength": 0.95,
    "control_type": "canny",
    "canny_low": 50,
    "canny_high": 100,
    "control_strength": 0.7,
    "seed": 0,
    "warp_period": [
        0,
        0.1
    ],
    "ada_period": [
        0.8,
        1
    ],
    "freeu_args": [
        1.1,
        1.2,
        1.0,
        0.2
    ]
}

**Comment by williamyang1991** [comment]
我印象里用的是比v30更低的版本

**Comment by zoeouyang2543** [comment]
> 我印象里用的是比v30更低的版本

好的，谢谢，我试试counterfeitV30_v30.safetensors 更低的版本看看。
还有一个问题，config文件有什么特别注意的吗？您这边用的是哪个config文件执行的呢

**Comment by williamyang1991** [comment]
"a_prompt": "RAW photo, subject, (high detailed skin:1.2), 8k uhd, dslr, soft lighting, high quality, film grain, Fujifilm XT3",
"n_prompt": "(deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers:1.4), (deformed, distorted, disfigured:1.3), poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, amputation",
是用于realistic vision的
卡通风格用
    "a_prompt": "best quality, extremely detailed",
    "n_prompt": "longbody, lowres, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality",

甚至extremely detailed可以去掉

**Comment by zoeouyang2543** [comment]
> "a_prompt": "RAW photo, subject, (high detailed skin:1.2), 8k uhd, dslr, soft lighting, high quality, film grain, Fujifilm XT3", "n_prompt": "(deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers:1.4), (deformed, distorted, disfigured:1.3), poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, amputation", 是用于realistic vision的 卡通风格用 "a_prompt": "best quality, extremely detailed", "n_prompt": "longbody, lowres, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality",
> 
> 甚至extremely detailed可以去掉

您好，按照你的指引，得到的结果还是很奇怪，我下载的是v2.5的版本

**Comment by zoeouyang2543** [comment]
> "a_prompt": "RAW photo, subject, (high detailed skin:1.2), 8k uhd, dslr, soft lighting, high quality, film grain, Fujifilm XT3", "n_prompt": "(deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers:1.4), (deformed, distorted, disfigured:1.3), poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, amputation", 是用于realistic vision的 卡通风格用 "a_prompt": "best quality, extremely detailed", "n_prompt": "longbody, lowres, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality",
> 
> 甚至extremely detailed可以去掉

您好，按照你的指引，得到的结果还是很奇怪，我下载的是v2.5的版本
会不会是某些参数需要配置呢，还是说合并模型和lora后调用，跟直接放在webui上使用差异还是很大的？
{
    "input": "/home/notebook/data/group/oyp/Rerender_A_Video/videos/pexels_antoni_shkraba_8048492_540x960_25fps.mp4",
    "output": "/home/notebook/data/group/oyp/Rerender_A_Video/videos/man/blend.mp4",
    "work_dir": "/home/notebook/data/group/oyp/Rerender_A_Video/videos/man",
    "key_subdir": "keys",
    "frame_count": 102,
    "interval": 10,
    "sd_model": "/home/notebook/data/group/oyp/Rerender_A_Video/models/countfeit_25_ghibli",
    "prompt": "a handsome man in cartoon style",
    "a_prompt": "best quality, extremely detailed",
    "n_prompt": "longbody, lowres, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality",
    "x0_strength": 0.75,
    "control_type": "canny",
    "canny_low": 50,
    "canny_high": 100,
    "control_strength": 0.7,
    "seed": 0,
    "warp_period": [
        0,
        0.1
    ],
    "ada_period": [
        1,
        1
    ]
}

**Comment by williamyang1991** [comment]
你的prompt也和我的不一样
我的是 ghibli style, a handsome man

我不太记得我当时用的canny还是HED，你可以都试一下

**Comment by zoeouyang2543** [comment]
> 你的prompt也和我的不一样 我的是 ghibli style, a handsome man
> 
> 我不太记得我当时用的canny还是HED，你可以都试一下

我都试过了，但是都得到的结果都不是你这边给到的examples，哈哈哈哈
会不会是某些参数的设置不一样呢，当时的json文件还有吗

**Comment by williamyang1991** [comment]
因为我离职回国了，服务器上很多文件就删掉了。
而且代码是中稿之后才整理的，整理前的代码还没有用json文件来指定标注，我基本都是用txt来记录实验设置的。
我翻了一下当时就记录了：
ghibli style, a handsome man, 0.7, 0.25, Counterfeit(Ghibli)
其中0.25对应1-"x0_strength"，0.7对应"control_strength"

**Comment by zoeouyang2543** [comment]
> 因为我离职回国了，服务器上很多文件就删掉了。 而且代码是中稿之后才整理的，整理前的代码还没有用json文件来指定标注，我基本都是用txt来记录实验设置的。 我翻了一下当时就记录了： ghibli style, a handsome man, 0.7, 0.25, Counterfeit(Ghibli) 其中0.25对应1-"x0_strength"，0.7对应"control_strength"

好的，谢谢您，祝好
